### PR TITLE
Add `LBResources` class to build Django resource settings

### PR DESCRIPTION
**Pull request by Scotchester**
## Checklist

- [x] Include a description of your pull request and instructions for the reviewer to verify your work.
- [x] Link to any issues this PR is related to.
- [ ] Create/update documentation. If not included, tell us why.
- [ ] List the environments / browsers in which you tested your changes.
- [x] Tests, linting, or other required checks are passing.
- [x] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../releases); good ones make that easier to scan.
  - PRs will be broadly categorized in the change log, but for even easier scanning, consider prefixing with a component name or other useful categorization, e.g., "BaseButton: fix layout bug", or "Storybook: Update dependencies".
- [x] PR has been tagged with a [SemVer](https://semver.org/) label and a [general category label](../blob/main/.github/release-drafter.config.yml#L23-L42), or skip-changelog.
  - These tags are used to do the aforementioned broad categorization in the change log and determine what the next release's version number should be.
  - [Release Drafter](https://github.com/marketplace/actions/release-drafter) will attempt to do the category labeling for you! Please double-check its work.

## Description

Another piece of nasa-jpl/launchbox#2

This currently mocks up what the management bridge API response would be when requesting details about a site's resources. It should be converted to a real API call when that API is available.

Also sets up https://pre-commit.ci for our linting/formatting checks.

### CODE REVIEW

**Comment by Scotchester** [comment]
Added a commit that replaces the boilerplate GH Actions linting workflow I had copied in that used npm (which this repo doesn't use) with the [pre-commit.ci](https://pre-commit.ci/) service.

Screenshot of pre-commit.ci run showing that it only took 4.3 seconds

Holy crap, that's fast!

**Comment by Scotchester** [comment]
Belatedly confirming that I pushed changes to adjust this PR per https://github.com/nasa-jpl/launchbox/issues/2#issuecomment-1220019087. It now creates the `LBResources` class for building Django settings dicts for `DATABASES` and `CACHES`.

**Comment by Scotchester** [comment]
@addisonhardy @laespinoza This is ready for review!

**Review by addisonhardy — APPROVED** [review]
LGTM

**Pull request merged**
